Remove Interface static
neo-project/Neo.Cryptography.BLS12_381 pull request #11
Opened 2024-01-06 13:58 UTC by shargon

@cschuchardt88 take a look to this solution

2024-01-06 14:07 UTC, cschuchardt88 requested changes

2024-01-06 14:07 UTC, cschuchardt88 commented on src/Neo.Cryptography.BLS12_381/INumber.cs
> +    T Pow(in T value);
This should be called `multiply`.

2024-01-06 14:15 UTC, shargon commented on src/Neo.Cryptography.BLS12_381/INumber.cs
> +    T Pow(in T value);
You are right

2024-01-06 14:17 UTC, shargon commented on src/Neo.Cryptography.BLS12_381/INumber.cs
> +    T Negate();
We can add `T One()`

2024-01-08 07:03 UTC, shargon commented
merge?

2024-01-08 15:49 UTC, Jim8y commented
@cschuchardt88

2024-01-09 00:10 UTC, cschuchardt88 commented
@shargon @Jim8y looks good

2024-01-09 04:34 UTC, Jim8y approved these changes

2024-01-09 06:33 UTC, merged